---
title: "Proteocheometrics modeling of Bitter Taste Receptors"
author: "Saw Simeon and Chanin Nantasenamat"
date: "October 14, 2015"
output: html_document
---




Principal components analysis fo natural bitter taste compounds
```{r}
library(caret)
library(paran)
library(grid)

set.seed(2222)
setwd("/Volumes/SAW SIMEON/Bitter/Padel_Descriptors/Natural/")
nature <- read.csv("Natural.csv", header = TRUE)
nature <- nature[-1]
nature <- nature[, -nearZeroVar(nature)]
paran(nature)
pca <- prcomp(nature, center = TRUE, scale. = TRUE, retx = TRUE)
summary(pca)
loadings <- pca$rotation[, 1:6]
print(loadings)
scores <- pca$x[, 1:6]
km <- kmeans(scores, center= 3, nstart = 5)
ggdata <- data.frame(scores, Cluster = km$cluster)

natural_pca_plot_scores <- ggplot(ggdata, aes(x = PC1, y = PC2, colour = Cluster)) +
  geom_point(aes(fill = factor(Cluster)), size = 5, shape = 20, pch = 21, alpha = 0.8) +
  ggtitle("Scores Plot ") +
  stat_ellipse(aes(fill = factor(Cluster)), colour = "black", 
               geom = "polygon", level = 0.95, alpha = 0.2) +
  guides(color = guide_legend("Cluster"), fill = guide_legend("Cluster")) +
  theme(
    legend.position = ("none"),
    panel.border = element_rect(linetype = "solid", colour = "black", fill = NA),
    axis.text.y = element_text(size = 15),
    axis.ticks.length = unit(0.3, "cm"),
    axis.text.x = element_text(size = 15),
    legend.title = element_blank(),
    axis.title.x = element_text(colour = "black", size = 20),
    axis.title.y =  element_text(color = "black", size = 20)) 
print(natural_pca_plot_scores)

##Loading plot
km <- kmeans(loadings, center = 3, nstart = 5)
ggdata <- data.frame(loadings, Cluster = km$cluster)
set.seed(2220)
natural_pca_plot_loadings <- ggplot(ggdata, aes(x = PC1, y = PC2, colour = Cluster)) +
  geom_point(aes(fill = factor(Cluster)), size = 5, shape = 20, pch = 21, alpha = 0.8) +
  ggtitle("Loading plot") +
  stat_ellipse(aes(fill = factor(Cluster)), colour = "black", geom= "polygon", level = 0.95,
               alpha = 0.2) +
  guides(color = guide_legend("Cluster"), fill = guide_legend("Cluster")) +
  theme(
    legend.position = ("none"),
    panel.border = element_rect(linetype = "solid", colour = "black", fill = NA, size = 1),
    axis.text.y = element_text(size = 15),
    axis.ticks.length = unit(0.3, "cm"),
    axis.text.x = element_text(size = 15),
    legend.title = element_text(size = 15),
    legend.title = element_blank(),
    axis.title.x = element_text(color = "black", size = 20),
    axis.title.y = element_text(color = "black", size = 20)) 
print(natural_pca_plot_loadings)
```



```{r}
setwd("/Volumes/SAW SIMEON/Bitter/Padel_Descriptors/Synthetic/")
synthetic <- read.csv("Synthetic.csv", header =  TRUE)
synthetic <- synthetic[-1]
synthetic <- nature[, -nearZeroVar(synthetic)]
paran(synthetic)
pca <- prcomp(synthetic, center = TRUE, scale. = TRUE, retx = TRUE)
summary(pca)
loadings <- pca$rotation[, 1:6]
print(loadings)
scores <- pca$x[, 1:6]
km <- kmeans(scores, center= 3, nstart = 5)
ggdata <- data.frame(scores, Cluster = km$cluster)

synthetic_pca_plot_scores <- ggplot(ggdata, aes(x = PC1, y = PC2, colour = Cluster)) +
  geom_point(aes(fill = factor(Cluster)), size = 5, shape = 20, pch = 21, alpha = 0.8) +
  ggtitle("Scores Plot ") +
  stat_ellipse(aes(fill = factor(Cluster)), colour = "black", 
               geom = "polygon", level = 0.95, alpha = 0.2) +
  guides(color = guide_legend("Cluster"), fill = guide_legend("Cluster")) +
  theme(
    legend.position = ("none"),
    panel.border = element_rect(linetype = "solid", colour = "black", fill = NA, size = 1),
    axis.text.y = element_text(size = 15),
    axis.ticks.length = unit(0.3, "cm"),
    axis.text.x = element_text(size = 15),
    legend.title = element_blank(),
    axis.title.x = element_text(colour = "black", size = 20),
    axis.title.y =  element_text(color = "black", size = 20)) 
print(synthetic_pca_plot_scores)
set.seed(200)
km <- kmeans(loadings, center = 3, nstart = 5)
ggdata <- data.frame(loadings, Cluster = km$cluster)
synthetic_pca_plot_loadings <- ggplot(ggdata, aes(x = PC1, y = PC2, colour = Cluster)) +
  geom_point(aes(fill = factor(Cluster)), size = 5, shape = 20, pch = 21, alpha = 0.8) +
  ggtitle("Loadings Plot") +
  stat_ellipse(aes(fill = factor(Cluster)), colour = "black", 
               geom = "polygon", level = 0.95, alpha = 0.2) +
  guides(color = guide_legend("Cluster"), fill = guide_legend("Cluster")) +
  theme(
    legend.position = ("none"),
    panel.border = element_rect(linetype = "solid", colour = "black", fill = NA, size = 1),
    axis.text.y = element_text(size =15),
    axis.ticks.length = unit(0.3, "cm"),
    axis.text.x = element_text(size = 15),
    legend.title = element_blank(),
    axis.title.x = element_text(color = "black", size = 20),
    axis.title.y = element_text(color = "black", size = 20))
print(synthetic_pca_plot_loadings)

setwd("/Volumes/SAW SIMEON/Bitter/")
```


```{r}
setwd("/Volumes/SAW SIMEON/Bitter/MEME_Motif/")
library(readxl)
protein <- read_excel("Motif_descriptors.xlsx")
protein <- protein[-1]
protein <- nature[, -nearZeroVar(protein)]
paran(protein)
pca <- prcomp(protein, center = TRUE, scale. = TRUE, retx = TRUE)
summary(pca)
loadings <- pca$rotation[, 1:5]
print(loadings)
scores <- pca$x[, 1:5]
km <- kmeans(scores, center= 3, nstart = 5)
ggdata <- data.frame(scores, Cluster = km$cluster)

protein_pca_plot_scores <- ggplot(ggdata, aes(x = PC1, y = PC2, colour = Cluster)) +
  geom_point(aes(fill = factor(Cluster)), size = 5, shape = 20, pch = 21, alpha = 0.8) +
  ggtitle("Scores Plot ") +
  stat_ellipse(aes(fill = factor(Cluster)), colour = "black", 
               geom = "polygon", level = 0.95, alpha = 0.2) +
  guides(color = guide_legend("Cluster"), fill = guide_legend("Cluster")) +
  theme(
    legend.position = ("none"),
    panel.border = element_rect(linetype = "solid", colour = "black", fill = NA),
    axis.text.y = element_text(size = 15),
    axis.ticks.length = unit(0.3, "cm"),
    axis.text.x = element_text(size = 15),
    legend.title = element_blank(),
    axis.title.x = element_text(colour = "black", size = 20),
    axis.title.y =  element_text(color = "black", size = 20)) 
print(protein_pca_plot_scores)
km <- kmeans(loadings, center = 3, nstart = 5)
ggdata <- data.frame(loadings, Cluster = km$cluster)
set.seed(200)
protein_pca_plot_loadings <- ggplot(ggdata, aes(x = PC1, y = PC2, colour = Cluster)) +
  geom_point(aes(fill = factor(Cluster)), size = 5, shape = 20, pch = 21, alpha = 0.8) +
  ggtitle("Loading Plot") + 
  stat_ellipse(aes(fill = factor(Cluster)), colour = "black",
               geom = "polygon", level = 0.95, alpha = 0.2) +
  guides(color = guide_legend("Cluster"), fill = guide_legend("Cluster")) +
  theme(
    legend.position = ("none"),
    panel.border = element_rect(linetype = "solid", colour = "black", fill = NA, size = 1),
    axis.text.y = element_text(size = 15),
    axis.ticks.length = unit(0.3, "cm"),
    axis.text.x = element_text(size = 15),
    legend.title = element_blank(),
    axis.title.x = element_text(colour = "black", size = 20),
    axis.title.y = element_text(colour = "black", size = 20))
print(protein_pca_plot_loadings)
setwd("/Volumes/SAW SIMEON/Bitter/")
```


```{r, echo = FALSE, eval = FALSE}

setwd("E:/Bitter")
library(readxl)
library(caret)
library(Rcpi)
data <- read_excel("BT_PCM_Data.xlsx")

Activity <- data$Activity
Activity <- as.factor(Activity)
compound <- data[, 4:310]
compound <- compound[, -nearZeroVar(compound)]


protein <- data[, 311:880]
protein <- protein[, -nearZeroVar(protein)]

compound[compound == "0"] <- -1
CxP <- getCPI(compound, protein, type = "tensorprod")
CxP <- as.data.frame(CxP)
dfcompound <- names(data.frame(compound[,1:43]))
dfprotein <- names(data.frame(protein[,1:504]))
compoundNamecross <- rep(dfcompound, each = 504)
proteinNamecross <- rep(dfprotein, times = 43)
label <- paste(compoundNamecross, proteinNamecross, sep="_")
colnames(CxP) <- label
PxP <- getCPI(protein, protein, type = "tensorprod")
proteinName2 <- rep(dfprotein, times = 504)
proteinName1 <- rep(dfprotein, each = 504)
label_protein <- paste(proteinName1, proteinName2, sep = "_")
colnames(PxP) <- label_protein
index <-  c(1, 41, 81, 121, 161, 201, 241, 281, 321, 361, 401, 441,
                     481, 521, 561, 601, 641, 681, 721, 761, 801, 841, 881,
                     921, 961, 1001, 1041, 1081, 1121, 1161, 1201, 1241, 1281,
                     1321, 1361, 1401, 1441, 1481, 1521)

protein_selfcross <- PxP[, -index]
transposedIndexed_protein <- t(protein_selfcross)
index1 <- which(duplicated(transposedIndexed_protein))
removed_duplicated_protein <- transposedIndexed_protein[-index1, ]
PxP <- t(removed_duplicated_protein)

CxC <- getCPI(compound, compound, type = "tensorprod")
compoundName2 <- rep(dfcompound, times = 39)
compoundName1 <- rep(dfcompound, each = 39)
label <- paste(compoundName1, compoundName2, sep = "_")
colnames(CxC) <- label
index3 <- c(1, 41, 81, 121, 161, 201, 241, 281, 321, 361, 401, 441,
              481, 521, 561, 601, 641, 681, 721, 761, 801, 841, 881,
              921, 961, 1001, 1041, 1081, 1121, 1161, 1201, 1241, 1281,
              1321, 1361, 1401, 1441, 1481, 1521)
compound_selfcross <- CxC[, -index3]
transposedIndexed_compound <- t(compound_selfcross)
index4 <- which(duplicated(transposedIndexed_compound))
removed_compound <- transposedIndexed_compound[-index4, ]
compound_finalcrossterms <- t(removed_compound)
CxC <- compound_finalcrossterms



```




```{r, echo=FALSE, eval = FALSE}


J48_training <- function(x,) {
  library(parallel)
  library(doSNOW)
  cl <- makeCluster(8)
  registerDoSNOW(cl)
  
  ok <- list(100)
  ok <- foreach(i = 1:100 ) %dopar% {
    in_train <- caret::createDataPartition(x$Activity, p = 0.80, list = FALSe)
    train <- x[in_train, ]
    test <- x[-in_train, ]
    model_train <- RWeka::J48(Activity ~., data = train)
    actual <- train$Activity
    prediciton <- predict(model_train , train)
    restuls <- caret::confusionMatrix(prediction, actual)
    resutls <- table(prediction, actual)
    results <- as.numeric(results)
    
  }
}

J48_10_CV <- function(x) {
  library(parallel)
  library(doSNOW)
  cl <- makeCluster(8)
  registerDoSNWO(cl)
  ok <- list(100)
  ok <- foreach(i = 1:100) %dopar% {
    in_train <- caret::createDataPartition(x$Activity, p = 0.80, list = FALSe)
    myData <- x[in_train, ]
    test <- x[-in_train, ]
    k = 10
    index <- sample(1:k, nrow(myData), replace = TRUE)
    folds <- 1:k
    myRes <- data.frame()
    for (j in 1:k)
      training <- subset(myDAta, index %in% )
  }
}
```

